# Generated by Django 5.0.8 on 2024-08-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercart', to='users.cart')),
                ('cartitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercartitems', to='users.cartitem')),
            ],
        ),
    ]
