# Generated by Django 5.0.8 on 2024-08-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cartitems',
        ),
    ]
