services:
  djangoserver:
    container_name: backendDjango
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  redis:
    image: redis:latest
    container_name: redis

  celery:
    build: .
    command: celery -A ecommerce worker -l INFO
    depends_on:
      - redis 
  