# Generated by Django 5.1 on 2024-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/2/2f/Blue_vacuum_cleaner.svg'),
        ),
    ]
